config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'home#index'

  namespace :manager do
    get '/', to: 'home#index'
    resources :interviews
  end

  devise_for :users, controllers: {registrations: 'users/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/interview.rb
class Interview < ApplicationRecord
  belongs_to :interviewer, class_name: 'User'

  has_many :interview_phases, dependent: :destroy

  def generate_candidate_token
    @candidate_token = Digest::MD5.hexdigest(@candidate_name + @candidate_email + Date.new.to_s)
  end
end

app/models/interview_phase.rb
class InterviewPhase < ApplicationRecord
  belongs_to :interview
  has_many :interview_tasks, dependent: :destroy
end

app/models/interview_task.rb
class InterviewTask < ApplicationRecord
  belongs_to :interview_phase
  has_one :language
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/phase_template.rb
class PhaseTemplate < ApplicationRecord
  has_many :task_templates, dependent: :destroy
end

app/models/task_template.rb
class TaskTemplate < ApplicationRecord
  belongs_to :phase_template
  has_one :language
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :interviews, foreign_key: 'interviewer_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    render 'home/index'
  end
end

app/controllers/manager/application_controller.rb
module Manager
  class ApplicationController < ::ApplicationController
    layout 'manager'
    before_action :authenticate_user!
  end
end

app/controllers/manager/home_controller.rb
class Manager::HomeController < Manager::ApplicationController
  def index
    render 'manager/home/index'
  end
end

app/controllers/manager/interviews_controller.rb
class Manager::InterviewsController < Manager::ApplicationController
  before_action :set_interview, only: [:show, :edit, :update, :destroy]

  # GET /interviews
  # GET /interviews.json
  def index
    @interviews = current_user.interviews
  end

  # GET /interviews/1
  # GET /interviews/1.json
  def show
  end

  # GET /interviews/new
  def new
    @interview = Interview.new
  end

  # GET /interviews/1/edit
  def edit
  end

  # POST /interviews
  # POST /interviews.json
  def create
    @interview = Interview.new(interview_params)

    respond_to do |format|
      if @interview.save
        format.html { redirect_to @interview, notice: 'Interview was successfully created.' }
        format.json { render :show, status: :created, location: @interview }
      else
        format.html { render :new }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interviews/1
  # PATCH/PUT /interviews/1.json
  def update
    respond_to do |format|
      if @interview.update(interview_params)
        format.html { redirect_to @interview, notice: 'Interview was successfully updated.' }
        format.json { render :show, status: :ok, location: @interview }
      else
        format.html { render :edit }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interviews/1
  # DELETE /interviews/1.json
  def destroy
    @interview.destroy
    respond_to do |format|
      format.html { redirect_to interviews_url, notice: 'Interview was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interview
      @interview = Interview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interview_params
      params.require(:interview).permit(:stats)
    end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/manager/home_helper.rb
module Manager::HomeHelper
end

app/helpers/manager/interviews_helper.rb
module Manager::InterviewsHelper
  def format_stats(interview)
    %w(未开始 题库面试 Live面试 不合格 通过)[interview.stats]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recruiter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'front', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar'%>
    <div style="padding-top:48px;">
      <%= yield %>
    </div>
    <%= render 'shared/footer'%>
  </body>
</html>

app/views/layouts/manager.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'manager', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'manager/shared/navbar'%>

    <div class="container-fluid">
      <div class="row">
        <%= render 'manager/shared/menubar'%>
        <!-- content -->
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="container offset-top-20">
  <footer>
    <p>&copy; 2017 Recruiter Coders Company, Inc.</p>
  </footer>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Recruiter Coder</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Welcome <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#"><%=current_user.email%></a></li>
              <li><%= link_to 'Manager', manager_path%></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Sign Out', destroy_user_session_path, method: 'delete'%></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path%></li>
        <% end %>
      </ul>
    </div><!--/.navbar-collapse -->
  </div>
</nav>