config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'home#index'

  namespace :manager do
    get '/', to: 'home#index'
    resources :interviews
  end

  devise_for :users, controllers: {registrations: 'users/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/manager/application_controller.rb
module Manager
  class ApplicationController < ::ApplicationController
    layout 'manager'
    before_action :authenticate_user!
  end
end

app/controllers/manager/home_controller.rb
class Manager::HomeController < Manager::ApplicationController
  def index
    render 'manager/home/index'
  end
end

app/controllers/manager/interviews_controller.rb
class Manager::InterviewsController < Manager::ApplicationController
  before_action :set_interview, only: [:show, :edit, :update, :destroy]

  # GET /interviews
  # GET /interviews.json
  def index
    @interviews = current_user.interviews
  end

  # GET /interviews/1
  # GET /interviews/1.json
  def show
  end

  # GET /interviews/new
  def new
    @interview = Interview.new
  end

  # GET /interviews/1/edit
  def edit
  end

  # POST /interviews
  # POST /interviews.json
  def create
    @interview = Interview.new(interview_params)

    respond_to do |format|
      if @interview.save
        format.html { redirect_to @interview, notice: 'Interview was successfully created.' }
        format.json { render :show, status: :created, location: @interview }
      else
        format.html { render :new }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interviews/1
  # PATCH/PUT /interviews/1.json
  def update
    respond_to do |format|
      if @interview.update(interview_params)
        format.html { redirect_to @interview, notice: 'Interview was successfully updated.' }
        format.json { render :show, status: :ok, location: @interview }
      else
        format.html { render :edit }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interviews/1
  # DELETE /interviews/1.json
  def destroy
    @interview.destroy
    respond_to do |format|
      format.html { redirect_to interviews_url, notice: 'Interview was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interview
      @interview = Interview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interview_params
      params.require(:interview).permit(:stats)
    end
end

app/helpers/manager/home_helper.rb
module Manager::HomeHelper
end

app/helpers/manager/interviews_helper.rb
module Manager::InterviewsHelper
  def format_stats(interview)
    %w(未开始 题库面试 Live面试 不合格 通过)[interview.stats]
  end
end

app/views/manager/interviews/_form.html.erb
<%= simple_form_for(@interview) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :stats %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/manager/interviews/_interview_item.html.erb
<table class="table table-hover">
  <% interviews.each do |interview| %>
    <tr>
      <td><%= interview.candidate_email%></td>
      <td><%= interview.candidate_name%></td>
      <td><%= format_stats(interview) %></td>
      <td><%= link_to '查看', manager_interview_path(interview) %></td>
      <td><%= link_to '删除', manager_interview_path(interview), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/manager/interviews/edit.html.erb
<h1>Editing Interview</h1>

<%= render 'form', interview: @interview %>

<%= link_to 'Show', @interview %> |
<%= link_to 'Back', manager_interviews_path %>

app/views/manager/interviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Interviews</h1>

<div class="panel panel-primary">
  <div class="panel-heading">待面试</div>
  <%= render 'interview_item', :interviews => @interviews.select{|x| x.stats == 0}%>
</div>


<div class="panel panel-info">
  <div class="panel-heading">面试中</div>
  <%= render 'interview_item', :interviews => @interviews.select{|x| [1,2].include? x.stats }%>
</div>


<div class="panel panel-success">
  <div class="panel-heading">已面试</div>
    <%= render 'interview_item', :interviews => @interviews.select{|x| x.stats > 2}%>
  </table>
</div>

<br>

<%= link_to 'New Interview', new_manager_interview_path %>

app/views/manager/interviews/new.html.erb
<h1>New Interview</h1>

<%= render 'form', interview: @interview %>

<%= link_to 'Back', manager_interviews_path %>

app/views/manager/interviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>邮箱:</strong>
  <%= @interview.candidate.email %>
</p>
<p>
  <strong>名称:</strong>
  <%= @interview.candidate.nick_name %>
</p>
<p>
  <strong>面试官:</strong>
  <%= @interview.interviewer.nick_name %>
</p>
<p>
  <strong>状态:</strong>
  <%= @interview.stats %>
</p>

<%= link_to 'Edit', edit_manager_interview_path(@interview) %> |
<%= link_to 'Back', manager_interviews_path %>